name: my_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6

  # Google Map + Location + Routing
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  http: ^1.4.0
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.0

  # Gợi ý địa điểm - dùng bản hỗ trợ http 1.x
  flutter_google_places_hoc081098: ^2.0.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  #Thong bao
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  permission_handler: ^11.0.0

  # Flutter map (dùng riêng, không đụng với Google Map)
#  flutter_map: ^6.2.1
#  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
